---
- hosts: db
  become: yes
  gather_facts: 0
  tasks:
      - name: update the system
        yum:
          name: '*'
          state: latest
        tags:
          - update
      - name: install httpd
        package:
          name: httpd
          state: present
        tags:
          - install
      - name: start the httpd Daemon
        systemd:
          name: httpd
          state: started
          enabled: yes
        tags:
          - daemon
      - name: copy index file to target
        copy: 
          src: index.html
          dest: /var/www/html/index.html
        tags:
          - file_copy
        notify: Restart Apache

  handlers:
      - name: Restart Apache
        systemd:
          name: httpd
          state: restarted






#yum update -y
#yum install httpd -y
#systemctl start httpd
#systemctl enable httpd
#cd /var/www/html
#touch index.html
#vi